package com.ms.dgpinnacle.business.entity;
// Generated 19-03-2024 15:48:26 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * LoanOfficer generated by hbm2java
 */
@Entity
@PrimaryKeyJoinColumn(name="id")
@Table(schema = "public", name = "loan_officer")
public class LoanOfficer extends Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cellphone;
	private String email;
	private String lastName;
	private String mailingAdd;
	private String name;
	private String nmls;
	private Set<LoanClient> loanClients = new HashSet<LoanClient>(0);
	private Set<Operation> operations = new HashSet<Operation>(0);

	public LoanOfficer() {
	}

	@Column(name = "cellphone", nullable = false, length = 20)
	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "last_name", nullable = false, length = 36)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "mailing_add", nullable = false, length = 75)
	public String getMailingAdd() {
		return this.mailingAdd;
	}

	public void setMailingAdd(String mailingAdd) {
		this.mailingAdd = mailingAdd;
	}

	@Column(name = "name", nullable = false, length = 36)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "nmls", nullable = false, length = 50)
	public String getNmls() {
		return this.nmls;
	}

	public void setNmls(String nmls) {
		this.nmls = nmls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanOfficer")
	public Set<LoanClient> getLoanClients() {
		return this.loanClients;
	}

	public void setLoanClients(Set<LoanClient> loanClients) {
		this.loanClients = loanClients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanOfficer")
	public Set<Operation> getOperations() {
		return this.operations;
	}

	public void setOperations(Set<Operation> operations) {
		this.operations = operations;
	}

}
